=== Ayaya-799/ses/WebContent/config/format.dtd
<?xml version="1.0" encoding = "GB2312" ?>

<!ELEMENT FormatDef (Format*)>

<!ELEMENT Format ( RecordFormat*)>
<!ATTLIST Format
	id CDATA #REQUIRED
	>

<!ELEMENT RecordFormat ( XMLHeadTagFormat?, (XMLTagFormat|XMLConstantTagFormat|XMLFullTagFormat|XMLEndTagFormat|IndexedCollectionFormat)*)>
<!ATTLIST RecordFormat
	dataName CDATA #IMPLIED
	>

<!ELEMENT XMLHeadTagFormat EMPTY>
<!ATTLIST XMLHeadTagFormat
	version CDATA #REQUIRED
	encoding CDATA #REQUIRED
	standalone CDATA #REQUIRED
	>
	
<!ELEMENT XMLTagFormat EMPTY>
<!ATTLIST XMLTagFormat
	tagName CDATA #REQUIRED
	>
	
<!ELEMENT IndexedCollectionFormat (RecordFormat)>
<!ATTLIST IndexedCollectionFormat
	dataName CDATA #REQUIRED
	times CDATA #REQUIRED
	>
<!ELEMENT KeyedCollectionFormat (RecordFormat)>
<!ATTLIST KeyedCollectionFormat
	dataName CDATA #REQUIRED
	>

<!ELEMENT XMLConstantTagFormat EMPTY>
<!ATTLIST XMLConstantTagFormat
	tagName CDATA #REQUIRED
	value CDATA #REQUIRED
	format CDATA #IMPLIED
	>

<!ELEMENT XMLFullTagFormat EMPTY>
<!ATTLIST XMLFullTagFormat
	tagName CDATA #REQUIRED
	dataName CDATA #REQUIRED
	>

<!ELEMENT XMLEndTagFormat EMPTY>
<!ATTLIST XMLEndTagFormat
	tagName CDATA #REQUIRED
	>

=== Ayaya-799/ses/WebContent/config/servicetranscfg.xml
<?xml version="1.0" encoding="GB2312"?>
<!DOCTYPE FormatDef SYSTEM "format.dtd">

<FormatDef>
 
  <!--合同列表查询接口-请求数据包格式需翻页-->
<Format id="listContract_req">
	<RecordFormat>
		<XMLHeadTagFormat version = "1.0" encoding = "GB2312" standalone="no"/>
		<XMLTagFormat tagName="CM2002"/>
		
			<!--包头-->
			<XMLTagFormat tagName="pub"/>
				<XMLConstantTagFormat tagName="TransNo" value="37001"/>
				<XMLFullTagFormat tagName="ID" dataName="AuthId"/>
				<XMLFullTagFormat tagName="Verify" dataName="VerifyStr"/>
				<XMLFullTagFormat tagName="Area" dataName="AreaCode"/>
				<XMLFullTagFormat tagName="SN" dataName="SerialNo"/>
				<XMLFullTagFormat tagName="SID" dataName="SysID"/>
				<XMLFullTagFormat tagName="Date" dataName="TransDate"/>
				<XMLFullTagFormat tagName="TP" dataName="TurnPage"/>
				<XMLFullTagFormat tagName="BR" dataName="BeginRow"/>
				<XMLFullTagFormat tagName="ER" dataName="EndRow"/>
			<XMLEndTagFormat tagName="pub"/>
			<!--包头-->
			
			<!--请求输入数据-->
			<XMLTagFormat tagName="in"/>
				<XMLFullTagFormat tagName="itm" dataName="EntrustClientCode"/><!--网银传入客户代码-->
			<XMLEndTagFormat tagName="in"/>
			<!--请求输入数据-->
			
		<XMLEndTagFormat tagName="CM2002"/>
	</RecordFormat>
</Format>

<!--合同列表查询接口-返回数据包格式翻页-->
<Format id="listContract_res">
	<RecordFormat>
		<XMLHeadTagFormat version = "1.0" encoding = "GB2312" standalone="no"/>
		<XMLTagFormat tagName="CM2002"/>
		
			<!--包头-->
			<XMLTagFormat tagName="pub"/>
				<XMLConstantTagFormat tagName="TransNo" value="37001"/>
				<XMLFullTagFormat tagName="SN" dataName="SerialNo"/>
				<XMLFullTagFormat tagName="TN" dataName="TransNo"/>
				<XMLFullTagFormat tagName="TS" dataName="TranStatus"/>
				<XMLFullTagFormat tagName="BR" dataName="BeginRow"/>
          				<XMLFullTagFormat tagName="ER" dataName="EndRow"/>
          				<XMLFullTagFormat tagName="RC" dataName="RecCount"/><!--记录总数-->
          				<XMLFullTagFormat tagName="ErrCode" dataName="ErrorCode"/>
          				<XMLFullTagFormat tagName="ErrMsg" dataName="ErrorMsg"/>				
			<XMLEndTagFormat tagName="pub"/>
			<!--包头-->
			
			<!--交易结果数据-->
			<XMLTagFormat tagName="out"/>				
				<XMLTagFormat tagName="itm"/>
					<IndexedCollectionFormat dataName="ContractList" times="*">
						<RecordFormat dataName="kColl">
							 <XMLTagFormat tagName="rd"/>
							 	<XMLFullTagFormat tagName="f" dataName="LoanClientCode"/><!--借款人客户代码-->
							 	<XMLFullTagFormat tagName="f" dataName="LoanClientName"/><!--借款人客户名称-->
							 	<XMLFullTagFormat tagName="f" dataName="ContractCode"/><!--合同号-->
							 	<XMLFullTagFormat tagName="f" dataName="ProtocolCode"/><!--委托协议号-->
							 	<XMLFullTagFormat tagName="f" dataName="LoanAreaName"/><!--贷款业务所在行名称-->
							 <XMLEndTagFormat tagName="rd"/>
						</RecordFormat>
					</IndexedCollectionFormat>
				<XMLEndTagFormat tagName="itm"/>
			<XMLEndTagFormat tagName="out"/>
			<!--交易结果数据-->
			
		<XMLEndTagFormat tagName="CM2002"/>
	</RecordFormat>
</Format>


<!--合同明细查询接口-请求数据包格式不翻页-->
<Format id="queryContract_req">
	<RecordFormat>
		<XMLHeadTagFormat version = "1.0" encoding = "GB2312" standalone="no"/>
		<XMLTagFormat tagName="CM2002"/>
		
			<!--包头-->
			<XMLTagFormat tagName="pub"/>
				<XMLConstantTagFormat tagName="TransNo" value="37002"/>
				<XMLFullTagFormat tagName="ID" dataName="AuthId"/>
				<XMLFullTagFormat tagName="Verify" dataName="VerifyStr"/>
				<XMLFullTagFormat tagName="Area" dataName="AreaCode"/>
				<XMLFullTagFormat tagName="SN" dataName="SerialNo"/>
				<XMLFullTagFormat tagName="SID" dataName="SysID"/>
				<XMLFullTagFormat tagName="Date" dataName="TransDate"/>				
			<XMLEndTagFormat tagName="pub"/>
			<!--包头-->
			
			<!--请求输入数据-->
			<XMLTagFormat tagName="in"/>
				<XMLFullTagFormat tagName="itm" dataName="LoanClientCode"/><!--借款人客户代码-->
				<XMLFullTagFormat tagName="itm" dataName="ContractCode"/><!--合同号-->
			<XMLEndTagFormat tagName="in"/>
			<!--请求输入数据-->
			
		<XMLEndTagFormat tagName="CM2002"/>
	</RecordFormat>
</Format>


<!--合同明细查询接口-返回数据包格式不翻页-->
<Format id="queryContract_res">
	<RecordFormat>
		<XMLHeadTagFormat version = "1.0" encoding = "GB2312" standalone="no"/>
		<XMLTagFormat tagName="CM2002"/>
		
			<!--包头-->
			<XMLTagFormat tagName="pub"/>
				<XMLConstantTagFormat tagName="TransNo" value="37002"/>
				<XMLFullTagFormat tagName="SN" dataName="SerialNo"/>
				<XMLFullTagFormat tagName="TN" dataName="TransNo"/>
				<XMLFullTagFormat tagName="TS" dataName="TranStatus"/>
				<XMLFullTagFormat tagName="BR" dataName="BeginRow"/>
          				<XMLFullTagFormat tagName="ER" dataName="EndRow"/>
          				<XMLFullTagFormat tagName="RC" dataName="RecCount"/><!--记录总数-->
				<XMLFullTagFormat tagName="ErrCode" dataName="ErrorCode"/>
          				<XMLFullTagFormat tagName="ErrMsg" dataName="ErrorMsg"/>
			<XMLEndTagFormat tagName="pub"/>
			<!--包头-->
			
			<!--交易结果数据-->
			<XMLTagFormat tagName="out"/>
				<XMLFullTagFormat tagName="itm" dataName="LoanClientCode"/><!--借款人代码-->
				<XMLFullTagFormat tagName="itm" dataName="LoanClientName"/><!--借款人名称-->
				<XMLFullTagFormat tagName="itm" dataName="EntrustAmount"/><!--申请委托金额-->
				<XMLFullTagFormat tagName="itm" dataName="EntrustCurrency"/><!--委托币种-->
				<XMLFullTagFormat tagName="itm" dataName="LoanCurrency"/><!--贷款币种-->
				<XMLFullTagFormat tagName="itm" dataName="LoanYearRate"/><!--贷款年利率-->
				<XMLFullTagFormat tagName="itm" dataName="FineRate"/><!--未按用途使用罚金比率-->
				<XMLFullTagFormat tagName="itm" dataName="LoanType"/><!--贷款方式-->
				<XMLFullTagFormat tagName="itm" dataName="ChargeClientCode"/><!--手续费付费人代码-->
				<XMLFullTagFormat tagName="itm" dataName="LoanTerm"/><!--贷款期限-->
				<XMLFullTagFormat tagName="itm" dataName="LoanDate"/><!--客户约定放款日-->
				<XMLFullTagFormat tagName="itm" dataName="RepayDate"/><!--客户约定还款日-->
				<XMLFullTagFormat tagName="itm" dataName="LoanSubject"/><!--贷款科目-->
				<XMLFullTagFormat tagName="itm" dataName="LoanPurpose"/><!--贷款用途-->
				<XMLFullTagFormat tagName="itm" dataName="LoanAreaName"/><!--贷款业务所在行名称-->
				<XMLTagFormat tagName="itm"/>
					<IndexedCollectionFormat dataName="LoanAccountList" times="*"><!--贷款账号记录组-->
						<RecordFormat dataName="kColl">
							 <XMLTagFormat tagName="rd"/>
							 	<XMLFullTagFormat tagName="f" dataName="LoanAccount"/><!--贷款账号-->
							 	<XMLFullTagFormat tagName="f" dataName="InterestAccount"/><!--付息账号-->
							 	<XMLFullTagFormat tagName="f" dataName="LoanSubject"/><!--科目号-->							 	
							 <XMLEndTagFormat tagName="rd"/>
						</RecordFormat>
					</IndexedCollectionFormat>
				<XMLEndTagFormat tagName="itm"/>
				
				<XMLTagFormat tagName="itm"/>
					<IndexedCollectionFormat dataName="RMBEntrustAccountList" times="*">
						<RecordFormat dataName="kColl">
							 <XMLTagFormat tagName="rd"/>
							 	<XMLFullTagFormat tagName="f" dataName="SettleAccount"/><!--结算账号-->
							 	<XMLFullTagFormat tagName="f" dataName="SettleAccountType"/><!--结算账号种类-->
							 	<XMLFullTagFormat tagName="f" dataName="LoanSubject"/><!--科目号-->							 	
							 <XMLEndTagFormat tagName="rd"/>
						</RecordFormat>
					</IndexedCollectionFormat>
				<XMLEndTagFormat tagName="itm"/>				
			<XMLEndTagFormat tagName="out"/>
			<!--交易结果数据-->
			
		<XMLEndTagFormat tagName="CM2002"/>
	</RecordFormat>
</Format>

<!--借据列表查询接口-请求数据包格式需翻页-->
<Format id="listDueBill_req">
	<RecordFormat>
		<XMLHeadTagFormat version = "1.0" encoding = "GB2312" standalone="no"/>
		<XMLTagFormat tagName="CM2002"/>
		
			<!--包头-->
			<XMLTagFormat tagName="pub"/>
				<XMLConstantTagFormat tagName="TransNo" value="37003"/>
				<XMLFullTagFormat tagName="ID" dataName="AuthId"/>
				<XMLFullTagFormat tagName="Verify" dataName="VerifyStr"/>
				<XMLFullTagFormat tagName="Area" dataName="AreaCode"/>
				<XMLFullTagFormat tagName="SN" dataName="SerialNo"/>
				<XMLFullTagFormat tagName="SID" dataName="SysID"/>
				<XMLFullTagFormat tagName="Date" dataName="TransDate"/>
				<XMLFullTagFormat tagName="TP" dataName="TurnPage"/>
				<XMLFullTagFormat tagName="BR" dataName="BeginRow"/>
				<XMLFullTagFormat tagName="ER" dataName="EndRow"/>
			<XMLEndTagFormat tagName="pub"/>
			<!--包头-->
			
			<!--请求输入数据-->
			<XMLTagFormat tagName="in"/>
				<XMLFullTagFormat tagName="itm" dataName="LoanClientCode"/><!--借款人代码-->
				<XMLFullTagFormat tagName="itm" dataName="ContractCode"/><!--合同号-->
			<XMLEndTagFormat tagName="in"/>
			<!--请求输入数据-->
			
		<XMLEndTagFormat tagName="CM2002"/>
	</RecordFormat>
</Format>

<!--借据列表查询接口-返回数据包格式翻页-->
<Format id="listDueBill_res">
	<RecordFormat>
		<XMLHeadTagFormat version = "1.0" encoding = "GB2312" standalone="no"/>
		<XMLTagFormat tagName="CM2002"/>
		
			<!--包头-->
			<XMLTagFormat tagName="pub"/>
				<XMLConstantTagFormat tagName="TransNo" value="37003"/>
				<XMLFullTagFormat tagName="SN" dataName="SerialNo"/>
				<XMLFullTagFormat tagName="TN" dataName="TransNo"/>
				<XMLFullTagFormat tagName="TS" dataName="TranStatus"/>
				<XMLFullTagFormat tagName="BR" dataName="BeginRow"/>
          				<XMLFullTagFormat tagName="ER" dataName="EndRow"/>
          				<XMLFullTagFormat tagName="RC" dataName="RecCount"/><!--记录总数-->
          				<XMLFullTagFormat tagName="ErrCode" dataName="ErrorCode"/>
          				<XMLFullTagFormat tagName="ErrMsg" dataName="ErrorMsg"/>
			<XMLEndTagFormat tagName="pub"/>
			<!--包头-->
			
			<!--交易结果数据-->
			<XMLTagFormat tagName="out"/>
				<XMLFullTagFormat tagName="itm" dataName="EntrustClientCode"/><!--委托人客户代码-->
				<XMLFullTagFormat tagName="itm" dataName="LoanClientCode"/><!--借款人客户代码-->
				<XMLFullTagFormat tagName="itm" dataName="LoanClientName"/><!--借款人客户名称-->
				<XMLFullTagFormat tagName="itm" dataName="ContractCode"/><!--合同号-->
				<XMLTagFormat tagName="itm"/>
					<IndexedCollectionFormat dataName="DueBillList" times="*">
